export const FEATURE_LIMITS = {
  FREE: {
    AI_PROPOSAL: 50,
    AI_CONTRACT: 5,
    RECURRING_INVOICE: 5,
    INVOICE_GENERATED: 200,
    PROJECT_CREATED: 10,
    ORGANISATION_CREATED: 3,
    TEAM_MEMBER_ADDED: 10,
  },
  STARTER: {
    AI_PROPOSAL: 300,
    AI_CONTRACT: 50,
    RECURRING_INVOICE: 20,
    INVOICE_GENERATED: 1000,
    PROJECT_CREATED: 50,
    ORGANISATION_CREATED: 10,
    TEAM_MEMBER_ADDED: 25,
  },
  GROWTH: {
    AI_PROPOSAL: 1000,
    AI_CONTRACT: 250,
    RECURRING_INVOICE: 100,
    INVOICE_GENERATED: 5000,
    PROJECT_CREATED: 200,
    ORGANISATION_CREATED: 25,
    TEAM_MEMBER_ADDED: 75,
  },
  PROFESSIONAL: {
    AI_PROPOSAL: 5000,
    AI_CONTRACT: 2000,
    RECURRING_INVOICE: -1,
    INVOICE_GENERATED: -1,
    PROJECT_CREATED: -1,
    ORGANISATION_CREATED: -1,
    TEAM_MEMBER_ADDED: -1,
  },
  ENTERPRISE: {
    AI_PROPOSAL: -1,
    AI_CONTRACT: -1,
    RECURRING_INVOICE: -1,
    INVOICE_GENERATED: -1,
    PROJECT_CREATED: -1,
    ORGANISATION_CREATED: -1,
    TEAM_MEMBER_ADDED: -1,
  }
} as const;

export type FeatureLimits = typeof FEATURE_LIMITS;
