-- Migration: make subscription nullable in UsageRecord
-- Generated by manual edit

BEGIN;

-- Allow subscriptionId to be NULL so usage records can be created when user has no subscription
ALTER TABLE "UsageRecord" ALTER COLUMN "subscriptionId" DROP NOT NULL;

COMMIT;
